### ISSUE TITLE
Missing feed items

### ISSUE THREAD

**Issue by amacfie** [m0wer/rssfilter#47]
I created
<https://rssfilter.sgn.space/api/v1/feed/90f03952f8cf4032b136b78cd5a83efd/https:/hnrss.org/frontpage> for the feed <https://hnrss.org/frontpage> a few days ago. At first it wasn't including all of the items from the source feed and now there aren't any items at all from the past 2 days. I think I opened one or two links. 

Thanks for the project!

**Comment by m0wer** [comment]
Hi! You found a very interesting bug :-)

https://github.com/m0wer/rssfilter/blob/062ffc72efce0ce23d5edd7ba83e8e509220f301/backend/app/tasks.py#L102-L109

The parser code, just considers new articles to those whose URL is not already present in the database. This is a bad decision. For feeds like this one, which has very similar content to other HN feeds, it creates this weird behavior. And for other news aggregators it could cause some articles to only be present in one of many feeds.

Thanks for the bug report. I'll fix it and let you know.

**Comment by m0wer** [comment]
It's working as expected now! https://rssfilter.sgn.space/api/v1/feed/90f03952f8cf4032b136b78cd5a83efd/https:/hnrss.org/frontpage

The order is just a bit weird due to old articles being added now, but will work normally from now on.

Once you mark ten articles as read, you'll start getting customized filtering. Then you will also be able to see a 2D representation of your read articles and their clusters: https://rssfilter.sgn.space/api/docs#/user/get_user_clusters_2d_v1_user_user__user_id__clusters_2d_get
